### ISSUE TITLE
Suggestion: Use Pi-Hole native scripts for adlist management

### ISSUE THREAD

**Issue by tigattack** [r-pufky/ansible_pihole#1]
Instead of running [SQLite commands to add to the user adlist](https://github.com/r-pufky/ansible_pihole/blob/main/tasks/db.yml#L12-L22), you could use Pi-Hole's native `pihole [-b|-w] [-d] domain1 [domain2...]` ([src](https://docs.pi-hole.net/guides/misc/whitelist-blacklist/)) commands to add to it.

Combined with `pihole -q -exact domain1` and some conditional logic, full user adlist management (as opposed to just additions) would be fairly simple.

The first line of `pihole -q -exact domain1` output is one of the following:
* `<space>Exact match found in exact whitelist`
* `<space>Exact match found in exact blacklist`
* `<spaceX2>[i] No exact results found for domain1 within the adlists`

The first line of `pihole -w [-d] domain1` output is one of the following:
* `<spaceX2>[i] domain1 already exists in whitelist, no need to add!`
* `<spaceX2>[i] Adding domain1 to the whitelist...`
* `<spaceX2>[i] Removing domain1 from the whitelist...`
* `<spaceX2>[i] domain1 already exists in blacklist, it has been moved to whitelist!`

Note: This was using `-w`. With `-b` the results are the same, but substitute `whitelist` for `blacklist` or, in the case of the final example, swap the terms.

A great side effect of such a change would be proper reporting of changed state, rather than always reporting as changed when running SQLite commands to add to the adlist, even if nothing has actually changed.

**Comment by r-pufky** [comment]
Thanks for the info -- I've left this open as a feature enhancement request.

I think that using the CLI pihole interface makes a *lot* more sense, as you're leaving any future DB schema changes up to the tool instead of manually changing them.

I think there is two parts to this change:
1. Submit a pull request that moves current functionality over to the pihole CLI command.
2. Submit an additional pull request that focuses on adding additional command set features.

I'll leave this open as a enhancement request. It would be excellent if you would like to submit a pull request for this -- otherwise, I'll work on getting the first pull request done when I have a chunk of time to work on it.

**Comment by r-pufky** [comment]
I have some free time this week to start digging into this.

**Comment by r-pufky** [comment]
I've updated the role, with the CLI modification disabled by default. Test out the role and enable CLI modifications (pihole_use_cli: true).

Let me know how it goes. Please re-open with comments detailing issues if you have any.

**Comment by tigattack** [comment]
Sorry for the delay, I only just got a chance to try this out. Really appreciate the change, it works great!
