### ISSUE TITLE
Make other `Conditional Forwarding` variables available

### ISSUE THREAD

**Issue by aleprovencio** [r-pufky/ansible_pihole#11]
Hey!
By now we are allowed to configure `Conditional Forwarding` state with `pihole_rev_server` but not its other variables.

Could you please also make available `pihole_rev_server_cidr`, `pihole_rev_server_target` and `pihole_rev_server_domain` ?

**Comment by r-pufky** [comment]
Thanks for the bug. I'll schedule it for the next major ansible pihole release since there is new variables being introduced. I am taking a few months off howver, so if I don't get to it in the next few days, I'll get to it when I get back in a few months.

Do you know what version of pihole these variables appeared (a link to documentation would be great). Thanks!

**Comment by aleprovencio** [comment]
Thanks for the reply!

I'm not quite sure but after some browsing I've found that it might have been added [here](https://github.com/pi-hole/pi-hole/commit/90a5a13197d9cb43d1f2daea39693a0e312d02cf), and the best official documentation I've found is [this one](https://docs.pi-hole.net/routers/fritzbox/#hostnames-instead-of-ip-addresses-in-pi-holes-web-interface-conditional-forwarding)

Let me know if a PR is desired and could maybe speed up a release :)

**Comment by r-pufky** [comment]
If you'd like to author a PR for it, please do!

**Comment by aleprovencio** [comment]
Here you go https://github.com/r-pufky/ansible_pihole/pull/12

**Comment by r-pufky** [comment]
Merged - will be in 2.0 release.

**Comment by r-pufky** [comment]
This is now live in 2.0.x
